import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#003535',
        'primary-container': '#0d4d4d',
        'primary-fixed': '#b4edec',
        'primary-fixed-dim': '#98d1d0',
        'on-primary': '#ffffff',
        'on-primary-container': '#85bdbc',
        'secondary': '#006c49',
        'secondary-container': '#6cf8bb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714d',
        'tertiary': '#65000a',
        'tertiary-container': '#8f0012',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ff958e',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-dim': '#d9dadb',
        'surface-tint': '#2e6767',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#404848',
        'outline': '#707978',
        'outline-variant': '#bfc8c8',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'gutter': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'base': '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 4px 12px rgba(13, 77, 77, 0.05)',
        'ambient-md': '0 8px 24px rgba(13, 77, 77, 0.08)',
      },
    },
  },
  plugins: [],
} satisfies Config;
